version: '3'

services:
  libmpeg7_build_service:
    image: krzysiekk44/libmpeg7:latest
    container_name: libmpeg7_build_container
    build:
      context: ""
      dockerfile: Dockerfile
    command: ./scripts/fire_up_build.sh
    restart: always
    volumes:
      - ./build:/project/build
    environment:
      - PYTHONUNBUFFERED=1