/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mpeg7_bridge_libmpeg7 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mpeg7_bridge_libmpeg7
 * Method:    extractDescriptor
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mpeg7_bridge_libmpeg7_extractDescriptor
        (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     com_mpeg7_bridge_libmpeg7
 * Method:    extractDescriptorFromData
 * Signature: (I[B[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mpeg7_bridge_libmpeg7_extractDescriptorFromData
        (JNIEnv *, jobject, jint, jbyteArray, jobjectArray);

/*
 * Class:     com_mpeg7_bridge_libmpeg7
 * Method:    calculateDistance
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mpeg7_bridge_libmpeg7_calculateDistance
        (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
