/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztv_mpeg7_libmpeg7pw */

#ifndef _Included_com_ztv_mpeg7_libmpeg7pw
#define _Included_com_ztv_mpeg7_libmpeg7pw
#ifdef __cplusplus
extern "C" {
#endif
    /*
    * Class:     com_ztv_mpeg7_libmpeg7pw
    * Method:    extractDescriptor
    * Signature: (ILjava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_com_ztv_mpeg7_libmpeg7pw_extractDescriptor
        (JNIEnv *, jobject, jint, jstring, jobjectArray);

    /*
    * Class:     com_ztv_mpeg7_libmpeg7pw
    * Method:    extractDescriptorFromData
    * Signature: (I[B[Ljava/lang/String;)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_com_ztv_mpeg7_libmpeg7pw_extractDescriptorFromData
        (JNIEnv *, jobject, jint, jbyteArray, jobjectArray);

    /*
    * Class:     com_ztv_mpeg7_libmpeg7pw
    * Method:    calculateDistance
    * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_com_ztv_mpeg7_libmpeg7pw_calculateDistance
        (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
