name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-22.04
    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
      
    - name: Find JNI path
      id: find-jni
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_OUTPUT
        echo "JNI_INCLUDE_DIR=$JAVA_HOME/include" >> $GITHUB_OUTPUT
        echo "JNI_MD_INCLUDE_DIR=$JAVA_HOME/include/linux" >> $GITHUB_OUTPUT

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DJAVA_AWT_INCLUDE_PATH="${{ steps.find-jni.outputs.JNI_INCLUDE_DIR }}" \
          -DJAVA_INCLUDE_PATH="${{ steps.find-jni.outputs.JNI_INCLUDE_DIR }}" \
          -DJAVA_INCLUDE_PATH2="${{ steps.find-jni.outputs.JNI_MD_INCLUDE_DIR }}"

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libmpeg7-ubuntu-${{ env.BUILD_TYPE }}
        path: |
          build/libmpeg7*
          build/mpeg7_app

  run-descriptors:
    name: Run MPEG-7 Descriptors
    needs: build-release
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: libmpeg7-ubuntu-Release
        path: build
        
    - name: Set execute permissions
      run: chmod +x build/mpeg7_app
        
    - name: Run MPEG-7 descriptors on lenna.png
      run: |
        echo "Running MPEG-7 descriptors on lenna.png"
        cd ${{ github.workspace }}
        for i in {1..10}; do
          echo "### Running descriptor $i ###"
          ./build/mpeg7_app $i resources/lenna.png
          echo ""
        done